FROM centos:centos7
MAINTAINER Kumar Siddhartha <k.siddhartha@hotmail.com>

#Setup container environment parameters
ENV DEBIAN_FRONTEND noninteractive
ENV INITRD No

#Prepare the image
RUN yum -y update

#Make our life easy with utilities
RUN yum install -y -q python-software-properties software-properties-common bash-completion wget nano \
curl libcurl3 libcurl3-dev build-essential


#Install JDK
RUN yum -y install java-1.7.0-openjdk

#Fetch Jenkins LTS
ENV JENKINS_VERSION 2.8
ENV JENKINS_HOME /jenkins

RUN mkdir -p /opt/jenkins2.8
RUN wget http://mirrors.jenkins-ci.org/war/$JENKINS_VERSION/jenkins.war -O /opt/jenkins2.8/jenkins.war
#RUN wget http://mirrors.jenkins-ci.org/war/$JENKINS_VERSION/jenkins.war -O /opt/jenkins2.8/$JENKINS_VERSION.war
RUN chmod 644 /opt/jenkins2.8/jenkins.war

#Install Node
RUN yum install -y epel-release
RUN yum install -y nodejs
RUN yum install -y npm

#Install git
RUN yum install -y git

#We always launch jenkins.
ENTRYPOINT ["java", "-jar", "/opt/jenkins2.8/jenkins.war", "--httpPort=9090"]
EXPOSE 9090

CMD [""]
